layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: GCP
    web_url: https://github.com/GoogleCloudPlatform/
    image_url: https://avatars0.githubusercontent.com/u/2810941?s=200&v=4

  - name: Unity3D
    web_url: https://github.com/Unity-Technologies
    image_url: https://avatars1.githubusercontent.com/u/426196?s=200&v=4

  - name: Firebase
    web_url: https://github.com/topics/firebase
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/firebase/firebase.png
